// Generated by scripts/build-lingui-runtime.ts. Do not edit by hand.
export const runtimeCatalogs = {
  "en": {
    "contact.brief.include.documents": [
      "Available drawings or photos"
    ],
    "contact.brief.include.location": [
      "Project location"
    ],
    "contact.brief.include.programme": [
      "Programme type"
    ],
    "contact.brief.include.stage": [
      "Current stage"
    ],
    "contact.brief.includeLabel": [
      "Useful information"
    ],
    "contact.brief.label": [
      "Project enquiry"
    ],
    "contact.brief.lead": [
      "Three fields are enough. The button opens your email app with a structured draft; nothing is sent automatically."
    ],
    "contact.brief.title": [
      "Prepare a clear project email."
    ],
    "contact.channel.algeria.detail": [
      "Primary project line"
    ],
    "contact.channel.algeria.label": [
      "Algeria office"
    ],
    "contact.channel.email.detail": [
      "Drawings, photos and project briefs"
    ],
    "contact.channel.email.label": [
      "Email"
    ],
    "contact.channel.international.detail": [
      "Direct international contact"
    ],
    "contact.channel.international.label": [
      "International line"
    ],
    "contact.eyebrow": [
      "Contact"
    ],
    "contact.form.emailSubject": [
      "New Igloo project enquiry"
    ],
    "contact.form.message": [
      "Project summary"
    ],
    "contact.form.messagePlaceholder": [
      "Location, programme, area, current stage and available documents..."
    ],
    "contact.form.name": [
      "Name"
    ],
    "contact.form.namePlaceholder": [
      "Your name"
    ],
    "contact.form.replyTo": [
      "Phone or email"
    ],
    "contact.form.submit": [
      "Prepare email"
    ],
    "contact.lead": [
      "Speak directly with the Igloo team in Bir Khadem. Send the location, programme and available documents; we will route the request to the right person."
    ],
    "contact.office.call": [
      "Call the office"
    ],
    "contact.office.label": [
      "Bir Khadem office"
    ],
    "contact.office.mapLabel": [
      "Map of the Igloo office in Bir Khadem"
    ],
    "contact.office.openMaps": [
      "Open in Maps"
    ],
    "contact.office.title": [
      "Our address in Algiers."
    ],
    "contact.title": [
      "Start a project conversation."
    ],
    "footer.navigation": [
      "Navigation"
    ],
    "footer.office": [
      "Office"
    ],
    "home.hero.phrase.build": [
      "Building the future"
    ],
    "home.hero.phrase.craft": [
      "Crafting the future"
    ],
    "home.hero.phrase.dream": [
      "Dreaming of the future"
    ],
    "nav.company": [
      "Company"
    ],
    "nav.contact": [
      "Contact"
    ],
    "nav.home": [
      "Home"
    ],
    "nav.projects": [
      "Projects"
    ],
    "nav.services": [
      "Services"
    ],
    "nav.tenders": [
      "Tenders"
    ],
    "project.architect": [
      "Architect"
    ],
    "project.chat": [
      "Discuss a project"
    ],
    "project.client": [
      "Client"
    ],
    "project.completion": [
      "Completion"
    ],
    "project.construction": [
      "Construction delivery"
    ],
    "project.details": [
      "Details & location"
    ],
    "project.facilities": [
      "Housing & infrastructure"
    ],
    "project.faq": [
      "Frequently asked questions"
    ],
    "project.formOfContract": [
      "Form of contract"
    ],
    "project.gallery": [
      "Project gallery"
    ],
    "project.location": [
      "Location"
    ],
    "project.nearby": [
      "What's around"
    ],
    "project.overview": [
      "Project overview"
    ],
    "project.projectType": [
      "Project type"
    ],
    "project.related": [
      "Featured projects"
    ],
    "project.repeatOrNew": [
      "Repeat / new"
    ],
    "project.status": [
      "Status"
    ],
    "projects.all": [
      "All projects"
    ],
    "projects.open": [
      "Open project"
    ],
    "projects.readMore": [
      "Read more"
    ],
    "projects.seeAll": [
      "See all projects"
    ],
    "shared.languageSelector": [
      "Language selector"
    ],
    "shared.next": [
      "Next"
    ],
    "shared.previous": [
      "Previous"
    ]
  },
  "fr": {
    "contact.brief.include.documents": [
      "Plans ou photos disponibles"
    ],
    "contact.brief.include.location": [
      "Localisation du projet"
    ],
    "contact.brief.include.programme": [
      "Type de programme"
    ],
    "contact.brief.include.stage": [
      "Phase actuelle"
    ],
    "contact.brief.includeLabel": [
      "Informations utiles"
    ],
    "contact.brief.label": [
      "Demande de projet"
    ],
    "contact.brief.lead": [
      "Trois champs suffisent. Le bouton ouvre votre application e-mail avec une demande structurée ; aucun message n’est envoyé automatiquement."
    ],
    "contact.brief.title": [
      "Préparez un e-mail de projet clair."
    ],
    "contact.channel.algeria.detail": [
      "Ligne principale projets"
    ],
    "contact.channel.algeria.label": [
      "Bureau Algérie"
    ],
    "contact.channel.email.detail": [
      "Plans, photos et dossiers de projet"
    ],
    "contact.channel.email.label": [
      "E-mail"
    ],
    "contact.channel.international.detail": [
      "Contact international direct"
    ],
    "contact.channel.international.label": [
      "Ligne internationale"
    ],
    "contact.eyebrow": [
      "Contact"
    ],
    "contact.form.emailSubject": [
      "Nouvelle demande de projet Igloo"
    ],
    "contact.form.message": [
      "Résumé du projet"
    ],
    "contact.form.messagePlaceholder": [
      "Localisation, programme, surface, état d’avancement et documents disponibles…"
    ],
    "contact.form.name": [
      "Nom"
    ],
    "contact.form.namePlaceholder": [
      "Votre nom"
    ],
    "contact.form.replyTo": [
      "Téléphone ou e-mail"
    ],
    "contact.form.submit": [
      "Préparer l’e-mail"
    ],
    "contact.lead": [
      "Échangez directement avec l’équipe Igloo à Bir Khadem. Envoyez la localisation, le programme et les documents disponibles ; nous orienterons votre demande vers la bonne personne."
    ],
    "contact.office.call": [
      "Appeler le bureau"
    ],
    "contact.office.label": [
      "Bureau de Bir Khadem"
    ],
    "contact.office.mapLabel": [
      "Carte du bureau Igloo à Bir Khadem"
    ],
    "contact.office.openMaps": [
      "Ouvrir dans Maps"
    ],
    "contact.office.title": [
      "Notre adresse à Alger."
    ],
    "contact.title": [
      "Parlons de votre projet."
    ],
    "footer.navigation": [
      "Navigation"
    ],
    "footer.office": [
      "Bureau"
    ],
    "home.hero.phrase.build": [
      "Construire l’avenir"
    ],
    "home.hero.phrase.craft": [
      "Façonner l’avenir"
    ],
    "home.hero.phrase.dream": [
      "Imaginer l’avenir"
    ],
    "nav.company": [
      "Entreprise"
    ],
    "nav.contact": [
      "Contact"
    ],
    "nav.home": [
      "Accueil"
    ],
    "nav.projects": [
      "Projets"
    ],
    "nav.services": [
      "Services"
    ],
    "nav.tenders": [
      "Appels d'offres"
    ],
    "project.architect": [
      "Architecte"
    ],
    "project.chat": [
      "Discuter d'un projet"
    ],
    "project.client": [
      "Client"
    ],
    "project.completion": [
      "Achèvement"
    ],
    "project.construction": [
      "Réalisation des travaux"
    ],
    "project.details": [
      "Détails et localisation"
    ],
    "project.facilities": [
      "Logements et infrastructures"
    ],
    "project.faq": [
      "Questions fréquentes"
    ],
    "project.formOfContract": [
      "Type de contrat"
    ],
    "project.gallery": [
      "Galerie du projet"
    ],
    "project.location": [
      "Localisation"
    ],
    "project.nearby": [
      "À proximité"
    ],
    "project.overview": [
      "Présentation du projet"
    ],
    "project.projectType": [
      "Nature du projet"
    ],
    "project.related": [
      "Projets à la une"
    ],
    "project.repeatOrNew": [
      "Récurrent / nouveau"
    ],
    "project.status": [
      "Statut"
    ],
    "projects.all": [
      "Tous les projets"
    ],
    "projects.open": [
      "Voir le projet"
    ],
    "projects.readMore": [
      "Lire la suite"
    ],
    "projects.seeAll": [
      "Voir tous les projets"
    ],
    "shared.languageSelector": [
      "Sélecteur de langue"
    ],
    "shared.next": [
      "Suivant"
    ],
    "shared.previous": [
      "Précédent"
    ]
  },
  "ar-DZ": {
    "contact.brief.include.documents": [
      "المخططات أو الصور المتاحة"
    ],
    "contact.brief.include.location": [
      "موقع المشروع"
    ],
    "contact.brief.include.programme": [
      "نوع البرنامج"
    ],
    "contact.brief.include.stage": [
      "المرحلة الحالية"
    ],
    "contact.brief.includeLabel": [
      "المعلومات المفيدة"
    ],
    "contact.brief.label": [
      "طلب مشروع"
    ],
    "contact.brief.lead": [
      "تكفي ثلاثة حقول. يفتح الزر تطبيق بريدك بمسودة منظمة، ولن تُرسل أي رسالة تلقائياً."
    ],
    "contact.brief.title": [
      "جهّز رسالة واضحة بشأن مشروعك."
    ],
    "contact.channel.algeria.detail": [
      "الخط الرئيسي للمشاريع"
    ],
    "contact.channel.algeria.label": [
      "مكتب الجزائر"
    ],
    "contact.channel.email.detail": [
      "مخططات وصور وملخصات المشاريع"
    ],
    "contact.channel.email.label": [
      "البريد الإلكتروني"
    ],
    "contact.channel.international.detail": [
      "اتصال دولي مباشر"
    ],
    "contact.channel.international.label": [
      "الخط الدولي"
    ],
    "contact.eyebrow": [
      "تواصل"
    ],
    "contact.form.emailSubject": [
      "استفسار جديد عن مشروع لدى Igloo"
    ],
    "contact.form.message": [
      "ملخص المشروع"
    ],
    "contact.form.messagePlaceholder": [
      "الموقع ونوع المشروع والمساحة والمرحلة الحالية والوثائق المتاحة…"
    ],
    "contact.form.name": [
      "الاسم"
    ],
    "contact.form.namePlaceholder": [
      "اسمك"
    ],
    "contact.form.replyTo": [
      "الهاتف أو البريد الإلكتروني"
    ],
    "contact.form.submit": [
      "تجهيز الرسالة"
    ],
    "contact.lead": [
      "تواصل مباشرة مع فريق Igloo في بئر خادم. أرسل الموقع ونوع المشروع والوثائق المتاحة، وسنحوّل طلبك إلى الشخص المختص."
    ],
    "contact.office.call": [
      "اتصل بالمكتب"
    ],
    "contact.office.label": [
      "مكتب بئر خادم"
    ],
    "contact.office.mapLabel": [
      "خريطة مكتب Igloo في بئر خادم"
    ],
    "contact.office.openMaps": [
      "فتح في الخرائط"
    ],
    "contact.office.title": [
      "عنواننا في الجزائر العاصمة."
    ],
    "contact.title": [
      "لنبدأ الحديث عن مشروعك."
    ],
    "footer.navigation": [
      "التنقل"
    ],
    "footer.office": [
      "المكتب"
    ],
    "home.hero.phrase.build": [
      "نبني المستقبل"
    ],
    "home.hero.phrase.craft": [
      "نصوغ المستقبل"
    ],
    "home.hero.phrase.dream": [
      "نتخيل المستقبل"
    ],
    "nav.company": [
      "الشركة"
    ],
    "nav.contact": [
      "اتصل بنا"
    ],
    "nav.home": [
      "الرئيسية"
    ],
    "nav.projects": [
      "المشاريع"
    ],
    "nav.services": [
      "الخدمات"
    ],
    "nav.tenders": [
      "المناقصات"
    ],
    "project.architect": [
      "المهندس المعماري"
    ],
    "project.chat": [
      "ناقش مشروع"
    ],
    "project.client": [
      "الزبون"
    ],
    "project.completion": [
      "الإنجاز"
    ],
    "project.construction": [
      "تسليم الأشغال"
    ],
    "project.details": [
      "التفاصيل والموقع"
    ],
    "project.facilities": [
      "السكن والبنية التحتية"
    ],
    "project.faq": [
      "الأسئلة المتكررة"
    ],
    "project.formOfContract": [
      "نوع العقد"
    ],
    "project.gallery": [
      "معرض المشروع"
    ],
    "project.location": [
      "الموقع"
    ],
    "project.nearby": [
      "وش كاين فالمحيط"
    ],
    "project.overview": [
      "نظرة عامة على المشروع"
    ],
    "project.projectType": [
      "نوع المشروع"
    ],
    "project.related": [
      "مشاريع مميزة"
    ],
    "project.repeatOrNew": [
      "إعادة / جديد"
    ],
    "project.status": [
      "الحالة"
    ],
    "projects.all": [
      "كل المشاريع"
    ],
    "projects.open": [
      "افتح المشروع"
    ],
    "projects.readMore": [
      "اقرأ أكثر"
    ],
    "projects.seeAll": [
      "شوف كل المشاريع"
    ],
    "shared.languageSelector": [
      "مبدّل اللغة"
    ],
    "shared.next": [
      "التالي"
    ],
    "shared.previous": [
      "السابق"
    ]
  },
  "tr": {
    "contact.brief.include.documents": [
      "Mevcut çizimler veya fotoğraflar"
    ],
    "contact.brief.include.location": [
      "Proje konumu"
    ],
    "contact.brief.include.programme": [
      "Proje türü"
    ],
    "contact.brief.include.stage": [
      "Mevcut aşama"
    ],
    "contact.brief.includeLabel": [
      "Faydalı bilgiler"
    ],
    "contact.brief.label": [
      "Proje talebi"
    ],
    "contact.brief.lead": [
      "Üç alanı doldurmanız yeterli. E-posta uygulamanızda düzenleyebileceğiniz bir taslak açılır; onayınız olmadan hiçbir şey gönderilmez."
    ],
    "contact.brief.title": [
      "Projenizin ayrıntılarını paylaşın."
    ],
    "contact.channel.algeria.detail": [
      "Ana proje hattı"
    ],
    "contact.channel.algeria.label": [
      "Cezayir ofisi"
    ],
    "contact.channel.email.detail": [
      "Çizimler, fotoğraflar ve proje özetleri"
    ],
    "contact.channel.email.label": [
      "E-posta"
    ],
    "contact.channel.international.detail": [
      "Doğrudan uluslararası iletişim"
    ],
    "contact.channel.international.label": [
      "Uluslararası hat"
    ],
    "contact.eyebrow": [
      "İletişim"
    ],
    "contact.form.emailSubject": [
      "Yeni Igloo proje talebi"
    ],
    "contact.form.message": [
      "Proje özeti"
    ],
    "contact.form.messagePlaceholder": [
      "Projenin konumu, kapsamı, büyüklüğü, mevcut aşaması ve elinizdeki belgeler…"
    ],
    "contact.form.name": [
      "Ad"
    ],
    "contact.form.namePlaceholder": [
      "Adınız"
    ],
    "contact.form.replyTo": [
      "Telefon veya e-posta"
    ],
    "contact.form.submit": [
      "E-postayı hazırla"
    ],
    "contact.lead": [
      "Bir Khadem’deki Igloo ekibiyle doğrudan görüşün. Projenizin konumunu, kapsamını ve elinizdeki belgeleri paylaşın; sizi doğru ekip arkadaşımıza yönlendirelim."
    ],
    "contact.office.call": [
      "Ofisi ara"
    ],
    "contact.office.label": [
      "Bir Khadem ofisi"
    ],
    "contact.office.mapLabel": [
      "Bir Khadem’deki Igloo ofisinin haritası"
    ],
    "contact.office.openMaps": [
      "Haritalarda aç"
    ],
    "contact.office.title": [
      "Cezayir’deki adresimiz."
    ],
    "contact.title": [
      "Projenizi konuşalım."
    ],
    "footer.navigation": [
      "Menü"
    ],
    "footer.office": [
      "Ofis"
    ],
    "home.hero.phrase.build": [
      "Geleceği inşa ediyoruz"
    ],
    "home.hero.phrase.craft": [
      "Geleceğe şekil veriyoruz"
    ],
    "home.hero.phrase.dream": [
      "Geleceği hayal ediyoruz"
    ],
    "nav.company": [
      "Kurumsal"
    ],
    "nav.contact": [
      "İletişim"
    ],
    "nav.home": [
      "Ana sayfa"
    ],
    "nav.projects": [
      "Projeler"
    ],
    "nav.services": [
      "Hizmetler"
    ],
    "nav.tenders": [
      "İhaleler"
    ],
    "project.architect": [
      "Mimar"
    ],
    "project.chat": [
      "Projenizi konuşalım"
    ],
    "project.client": [
      "İşveren"
    ],
    "project.completion": [
      "Tamamlanma"
    ],
    "project.construction": [
      "Yapım süreci"
    ],
    "project.details": [
      "Detaylar ve konum"
    ],
    "project.facilities": [
      "Konut ve altyapı"
    ],
    "project.faq": [
      "Sıkça sorulan sorular"
    ],
    "project.formOfContract": [
      "Sözleşme türü"
    ],
    "project.gallery": [
      "Proje galerisi"
    ],
    "project.location": [
      "Konum"
    ],
    "project.nearby": [
      "Çevrede neler var"
    ],
    "project.overview": [
      "Projeye genel bakış"
    ],
    "project.projectType": [
      "Proje türü"
    ],
    "project.related": [
      "Öne çıkan projeler"
    ],
    "project.repeatOrNew": [
      "Tekrarlanan / yeni"
    ],
    "project.status": [
      "Durum"
    ],
    "projects.all": [
      "Tüm projeler"
    ],
    "projects.open": [
      "Projeyi incele"
    ],
    "projects.readMore": [
      "Devamını oku"
    ],
    "projects.seeAll": [
      "Tüm projeleri gör"
    ],
    "shared.languageSelector": [
      "Dil seçimi"
    ],
    "shared.next": [
      "Sonraki"
    ],
    "shared.previous": [
      "Önceki"
    ]
  }
} as const;
