import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const LOCALES = ['en', 'fr', 'ar-DZ', 'tr'] as const;
const OUTPUT = path.join(ROOT, 'src', 'i18n', 'catalogs.generated.ts');

async function compiledCatalog(locale: (typeof LOCALES)[number]) {
  const file = path.join(ROOT, 'src', 'locales', locale, 'messages.js');
  const source = await readFile(file, 'utf8');
  const match = source.match(/JSON\.parse\(("(?:\\.|[^"\\])*")\)/su);
  if (!match?.[1]) throw new Error(`Could not read compiled Lingui catalog for ${locale}.`);
  return JSON.parse(JSON.parse(match[1]) as string) as Record<string, unknown>;
}

async function main() {
  const catalogs = Object.fromEntries(await Promise.all(
    LOCALES.map(async (locale) => [locale, await compiledCatalog(locale)]),
  ));
  const output = `// Generated by scripts/build-lingui-runtime.ts. Do not edit by hand.\nexport const runtimeCatalogs = ${JSON.stringify(catalogs, null, 2)} as const;\n`;
  await writeFile(OUTPUT, output, 'utf8');
  process.stdout.write(`Generated ${path.relative(ROOT, OUTPUT)}.\n`);
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
